# Generated by Django 3.1.4 on 2020-12-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_location',
            field=models.FloatField(null=True),
        ),
    ]
