# Generated by Django 3.1.4 on 2020-12-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_organization_org_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='org_location',
        ),
    ]
