# Generated by Django 3.1.4 on 2021-03-14 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210315_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='punch_in_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_out_time',
        ),
    ]
