# Generated by Django 3.1.4 on 2021-02-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_attendance_complaintbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='date',
            new_name='punch_in_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_out_time',
            field=models.DateTimeField(default=None),
        ),
    ]
