# Generated by Django 3.1.4 on 2021-01-05 16:18

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_organization_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='geoLocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_address',
            field=django_google_maps.fields.AddressField(max_length=255, null=True, verbose_name='Organization Address'),
        ),
    ]
