# Generated by Django 3.1.4 on 2021-02-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210216_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_out_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
