# Generated by Django 3.1.4 on 2021-01-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210106_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='geoLocation',
        ),
    ]
