# Generated by Django 3.1.4 on 2021-02-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210217_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='punch_in_time',
        ),
    ]
