# Generated by Django 3.1.4 on 2021-02-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_attendance_punch_in_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='punch_in_time',
        ),
    ]
