# Generated by Django 3.1.4 on 2021-01-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_organization_geolocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='geoLocation',
        ),
    ]
