# Generated by Django 3.1.4 on 2021-01-05 22:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_organization_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='geoLocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, max_length=100, null=True, srid=4326),
        ),
    ]
