# Generated by Django 3.1.4 on 2021-01-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210106_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='geoLocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
