# Generated by Django 3.1.4 on 2021-01-06 00:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210106_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='geoLocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, max_length=100, null=True, srid=4326),
        ),
    ]
