# Generated by Django 3.1.4 on 2021-01-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20210106_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_address',
            field=models.CharField(max_length=255, null=True, verbose_name='Organization Address'),
        ),
    ]
