# Generated by Django 3.1.4 on 2020-12-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='position',
        ),
        migrations.AddField(
            model_name='position',
            name='tag',
            field=models.ManyToManyField(related_name='positiontag', to='account.Tag'),
        ),
    ]
