# Generated by Django 3.1.4 on 2020-12-04 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20201204_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owned By'),
        ),
    ]
