# Generated by Django 3.1.4 on 2020-12-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20201204_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='job_posting',
            field=models.BooleanField(default=False),
        ),
    ]
