# Generated by Django 3.1.4 on 2020-12-04 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_position_job_posting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='account.organization', verbose_name='Owned By'),
        ),
        migrations.AlterField(
            model_name='position',
            name='job_posting',
            field=models.BooleanField(default=False, verbose_name='Post as Job'),
        ),
    ]
