# Generated by Django 3.1.4 on 2020-12-05 14:38

import account.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20201205_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='job_posting',
            field=models.BooleanField(default=False, verbose_name='Open Position'),
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='applications', validators=[account.validators.validate_file_extension])),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.position')),
            ],
        ),
    ]
