# Generated by Django 3.1.4 on 2020-12-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20201205_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
