# Generated by Django 3.1.4 on 2020-12-05 16:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_delete_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_email', models.CharField(max_length=20, verbose_name='Email')),
                ('candidate_name', models.CharField(max_length=20, verbose_name='Name')),
                ('candidate_phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('cadidate_address', models.TextField(default=None)),
                ('filename', models.FileField(upload_to='applications', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.position')),
            ],
        ),
    ]
