# Generated by Django 3.1.4 on 2020-12-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='cadidate_address',
            new_name='candidate_address',
        ),
    ]
