# Generated by Django 3.1.4 on 2020-12-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20201216_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.AddField(
            model_name='organization',
            name='org_address',
            field=models.CharField(max_length=255, null=True, verbose_name='Organization Address'),
        ),
    ]
