# Generated by Django 3.1.4 on 2020-12-19 12:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20201216_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='responsibility',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
