# Generated by Django 3.1.4 on 2021-02-16 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetail',
            name='end_time',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
